/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-07 13:41:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class doctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>doctor join</title>\r\n");
      out.write("<style>\r\n");
      out.write(".log {\r\n");
      out.write("\tfont-size : 37px;\r\n");
      out.write("\tcolor : rgb(68, 114, 196);\r\n");
      out.write("\tmargin-bottom : 50px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:430px;\r\n");
      out.write("\ttop : 60px;\r\n");
      out.write("}\r\n");
      out.write(".lTitle {\r\n");
      out.write("\tfont-size : 18px;\r\n");
      out.write("\tcolor : rgb(68, 114, 196);\r\n");
      out.write("\tpadding-bottom : 10px;\r\n");
      out.write("\tpadding-left : 50px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".content {\r\n");
      out.write("\twidth : 450px;\r\n");
      out.write("\theight : 40px;\r\n");
      out.write("\tbox-shadow:none;\r\n");
      out.write("\tbackground-color : rgb(240,245,254);\r\n");
      out.write("\tborder : 2px solid rgb(197, 219, 254);\r\n");
      out.write("\tmargin : 0 50px 30px 50px;\r\n");
      out.write("\topacity : 65%;\r\n");
      out.write("\tpadding-left : 10px;\r\n");
      out.write("}\r\n");
      out.write(".input1{\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight : 40px;\r\n");
      out.write("\tbox-shadow:none;\r\n");
      out.write("\tmargin-top : 40px;\r\n");
      out.write("\tborder : 1px solid rgb(68, 114, 196);\r\n");
      out.write("\tcolor : rgb(68, 114, 196);\r\n");
      out.write("\tfont-size : 17px;\r\n");
      out.write("}\r\n");
      out.write(".t {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\ttop : 60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<form action=\"joinProc.jsp\" method=\"post\">\r\n");
      out.write("<center>\r\n");
      out.write("<div class=\"log\"> Join</div>\r\n");
      out.write("<input type=\"hidden\" name=\"nd\" value=\"d\">\r\n");
      out.write("<table width=\"400px\" class=\"t\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" width=\"200px\" class=\"lTitle\">이메일</td>\r\n");
      out.write("\t\t<td colspan=\"3\" width=\"200px\" class=\"lTitle\">병원명</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"email\"></td>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"hospital\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 비밀번호 </td>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 병원 번호 </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"password\"></td>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"htel\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 이름 </td>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 학력/자격 </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"school\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 생년월일 </td>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 전공 </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"birth\"></td>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"major\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 번호 </td>\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"lTitle\"> 사진 </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"tel\"></td>\r\n");
      out.write("\t\t<td colspan=\"3\"><input class=\"content\" type=\"text\" name=\"picture\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"6\" align=\"center\">\r\n");
      out.write(" \t\t\t<input class=\"input1\" type=\"button\" value=\"회원가입\"\r\n");
      out.write(" \t\t\tonclick=\"location.href='loginForm.jsp'\"\r\n");
      out.write(" \t\t\t");
      out.write(">\r\n");
      out.write(" \t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
