/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-10 08:54:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.medicine;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class medicine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>pill</title>\r\n");
      out.write("<style>\r\n");
      out.write(".pic{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tbottom : 33px;\r\n");
      out.write("}\r\n");
      out.write(".pill {\r\n");
      out.write("\theight : 150px;\r\n");
      out.write("\twidth : 250px;\r\n");
      out.write("}\r\n");
      out.write(".pname{\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\tfont-size : 18px;\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("\tcolor : rgb(127, 127, 127);\r\n");
      out.write("}\r\n");
      out.write(".pinfo{\r\n");
      out.write("\tfont-size : 15px;\r\n");
      out.write("\ttext-align : center;\r\n");
      out.write("\tcolor : rgb(127, 127, 127)\r\n");
      out.write("}\r\n");
      out.write(".buy{\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("\tmargin : 0 55px 0 55px;\r\n");
      out.write("}\r\n");
      out.write(".input1{\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\twidth : 250px;\r\n");
      out.write("\theight : 40px;\r\n");
      out.write("\tbox-shadow:none;\r\n");
      out.write("\tborder : 1px solid red;\r\n");
      out.write("\tcolor : red;\r\n");
      out.write("\tfont-size : 17px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<img src=\"../img/pill.png\" class=\"pic\" style=\"max-width:100%; height:auto;\">\r\n");
      out.write("<center>\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr height = \"200px\">\r\n");
      out.write("\t\t<td width=\"360px\" align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"../img/easy.PNG\" class=\"pill\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"360px\" align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"../img/tylenol.PNG\" class=\"pill\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"360px\" align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"../img/tenten.png\" class=\"pill\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"360px\" align=\"center\">\r\n");
      out.write("\t\t\t<img src=\"../img/hoosi.PNG\" class=\"pill\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"20px\">\r\n");
      out.write("\t\t<td class=\"pname\"> 이지엔6 이브\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pname\"> 타이레놀\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pname\"> 텐텐\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pname\"> 후시딘\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"60px\">\r\n");
      out.write("\t\t<td class=\"pinfo\"> 진통제\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pinfo\"> 진통제\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pinfo\"> 성장, 발육\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td  class=\"pinfo\"> 상처 연고\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"buy\">\r\n");
      out.write(" \t<input class=\"input1\" type=\"submit\" value=\"구매하기\"\r\n");
      out.write(" \t\tonclick=\"location.href='medicineSel.jsp?pname=이지엔6 이브&price=3500&pic=../img/easy.PNG'\">\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"buy\">\r\n");
      out.write(" \t<input class=\"input1\" type=\"button\" value=\"구매하기\"\r\n");
      out.write(" \t\tonclick=\"location.href='medicineSel.jsp?pname=타이레놀&price=3000&pic=../img/tylenol.PNG'\">\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"buy\">\r\n");
      out.write(" \t<input class=\"input1\" type=\"button\" value=\"구매하기\"\r\n");
      out.write(" \t\tonclick=\"location.href='medicineSel.jsp?pname=텐텐&price=20000&pic=../img/tenten.png'\">\r\n");
      out.write(" </div>\r\n");
      out.write(" <div class=\"buy\">\r\n");
      out.write(" \t<input class=\"input1\" type=\"button\" value=\"구매하기\"\r\n");
      out.write(" \t\tonclick=\"location.href='medicineSel.jsp?pname=후시딘&price=3500&pic=../img/hoosi.PNG'\">\r\n");
      out.write(" </div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
