/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-08 07:07:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.medicine;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class medicineSel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".pill{\r\n");
      out.write("\tmargin-left : 100px;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight : 230px;\r\n");
      out.write("}\r\n");
      out.write(".info {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tbottom : 30px;\r\n");
      out.write("}\r\n");
      out.write(".iTitle {\r\n");
      out.write("\tpadding : 35px 0 10px 20px;\r\n");
      out.write("\tborder-bottom : 2px solid rgb(68, 114, 196);\r\n");
      out.write("\tfont-size : 20px;\r\n");
      out.write("\tcolor : rgb(127, 127, 127);\r\n");
      out.write("}\r\n");
      out.write(".product {\r\n");
      out.write("\tpadding-top : 45px;\r\n");
      out.write("\tpadding-left : 40px;\r\n");
      out.write("\tfont-size : 21px;\r\n");
      out.write("\tcolor : rgb(89, 89, 89);\r\n");
      out.write("}\r\n");
      out.write(".price {\r\n");
      out.write("\tpadding-bottom : 30px;\r\n");
      out.write("\tpadding-left : 40px;\r\n");
      out.write("\tfont-size : 21px;\r\n");
      out.write("\tcolor : rgb(89, 89, 89);\r\n");
      out.write("}\r\n");
      out.write(".money {\r\n");
      out.write("\tpadding-bottom : 30px;\r\n");
      out.write("\tfont-size : 19px;\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("}\r\n");
      out.write(".pnum {\r\n");
      out.write("\tpadding-bottom : 35px;\r\n");
      out.write("\tpadding-left : 45px;\r\n");
      out.write("\tcolor : rgb(127, 127, 127);\r\n");
      out.write("\tfont-size : 19px;\r\n");
      out.write("}\r\n");
      out.write(".pput{\r\n");
      out.write("\twidth : 100px;\r\n");
      out.write("\theight : 25px;\r\n");
      out.write("\tmargin-right : 20px;\r\n");
      out.write("}\r\n");
      out.write(".lline{\r\n");
      out.write("\tborder-left : 1px solid rgb(68, 114, 196);\r\n");
      out.write("\twidth : 300px;\r\n");
      out.write("\theight : 200px;\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tleft : 300px;\r\n");
      out.write("\tbottom : 230px;\r\n");
      out.write("}\r\n");
      out.write(".sub {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\ttop : 65px;\r\n");
      out.write("\twidth : 150px;\r\n");
      out.write("\theight : 50px;\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\tborder : 1px solid rgb(68, 114, 196);\r\n");
      out.write("\tcolor : rgb(68, 114, 196);\r\n");
      out.write("\tfont-size : 19px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<form action=\"deliverForm.jsp\" method=\"post\">\r\n");
      out.write("<center>\r\n");

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<table class=\"info\" width=\"1200px\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"2\" class=\"iTitle\">상품정보</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"200px\">\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"200px\" rowspan=\"4\"> <img src=\"");
      out.print(request.getParameter("pic"));
      out.write("\" class=\"pill\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"pic\" value=\"");
      out.print(request.getParameter("pic"));
      out.write("\"> </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"product\">상품명 &nbsp : &nbsp ");
      out.print(request.getParameter("pname"));
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"pname\" value=\"");
      out.print(request.getParameter("pname"));
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\t\r\n");
      out.write("\t\t<td class=\"price\">가격 &nbsp : &nbsp");
      out.print(request.getParameter("price"));
      out.write("원\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"price\" value=\"");
      out.print(request.getParameter("price"));
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td class=\"pnum\"> <input class=\"pput\" type=\"text\" name=\"pnum\" value=\"1\" onfocus=\"this.value=''\">개 </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div class=\"lline\">\r\n");
      out.write("\t<input type=\"submit\" class=\"sub\" value=\"주문하기\">\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
