/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2020-06-01 13:48:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap');\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("}\r\n");
      out.write("header {\r\n");
      out.write("\theight : 43px;\r\n");
      out.write("\tfont-family : 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".title\r\n");
      out.write("{\r\n");
      out.write("\tmargin : 0px;\r\n");
      out.write("\tfont-size : 20px;\r\n");
      out.write("\tbackground-color : rgb(68,114,196);\r\n");
      out.write("\theight : 63px;\r\n");
      out.write("\tcolor : white;\r\n");
      out.write("}\r\n");
      out.write(".top {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\ttop : 8px;\r\n");
      out.write("\tleft : 10px;\r\n");
      out.write("}\r\n");
      out.write(".right\r\n");
      out.write("{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\ttop : -45px;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\tmargin-right : 20px;\r\n");
      out.write("\ttext-align : right;\r\n");
      out.write("\tfont-size : 18px;\r\n");
      out.write("\tcolor : white;\r\n");
      out.write("}\r\n");
      out.write(".login\r\n");
      out.write("{\r\n");
      out.write("\tcolor : rgb(0,32,96);\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("}\r\n");
      out.write(".ta{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tbottom : 4px;\r\n");
      out.write("}\r\n");
      out.write(".sq {\r\n");
      out.write("\twidth : 20px;\r\n");
      out.write("\theight : 20px;\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\tborder : none;\r\n");
      out.write("\tcolor : rgb(68,114,196);\r\n");
      out.write("\tpadding : 17px 5px 5px 18px;\r\n");
      out.write("\tfloat : top;\r\n");
      out.write("\tmargin-left  : 30px;\r\n");
      out.write("\tfont-family : '바탕';\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("\tfont-size : 24px;\r\n");
      out.write("}\r\n");
      out.write(".com {\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tleft : 63px;\r\n");
      out.write("\tbottom : 36px;\r\n");
      out.write("\tfont-family : '바탕';\r\n");
      out.write("\tfont-weight : bold;\r\n");
      out.write("\tfont-size : 24px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t<table class=\"top\">\r\n");
      out.write("\t\t<tr onclick=\"location.href='../main/main.jsp'\">\r\n");
      out.write("\t\t\t<div class=\"sq\">의</div>\r\n");
      out.write("\t\t\t<td class=\"com\">사 소통</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"right\">\r\n");
      out.write("\t<table class=\"ta\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td width=\"170\" onclick=\"location.href='../treat/writeList.jsp'\">진단받기</td>\r\n");
      out.write("\t\t<td width=\"170\">진료하기</td>\r\n");
      out.write("\t\t<td width=\"170\" onclick=\"location.href='../medicine/medicine.jsp'\">처방받기</td>\r\n");
      out.write("\t\t<td width=\"170\" onclick=\"location.href='../my/myPage.jsp'\">건강기록</td>\r\n");
		
		request.setCharacterEncoding("utf-8");

		String name = (String)application.getAttribute("name");
		if(name!=null && !name.equals("guest")){

      out.write("\r\n");
      out.write("\t\t\t<td class=\"login\" width=\"140\" onclick=\"location.href='../login/logout.jsp'\"> ");
      out.print(name);
      out.write(" 님 </td>\r\n");

		}
		else{

      out.write("\r\n");
      out.write("\t\t<td class=\"login\" width=\"140\" onclick=\"location.href='../login/loginForm.jsp'\">Login</td>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
