/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-12-05 07:44:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.treat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wright_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>write</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("}\r\n");
      out.write("hr{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tbottom : 26px;\r\n");
      out.write("\tborder-color : rgb(197, 218, 247);\r\n");
      out.write("}\r\n");
      out.write(".content {\r\n");
      out.write("\tmargin-left : 5px;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("}\r\n");
      out.write(".write {\r\n");
      out.write("\tmargin-top : 120px;\r\n");
      out.write("\t border-collapse: collapse;\r\n");
      out.write("\t border-color : rgb(200,200,200);\r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write(".submit{\r\n");
      out.write("\tposition : relative;\r\n");
      out.write("\tbottom : 620px;\r\n");
      out.write("\tleft : 475px;\r\n");
      out.write("\tbackground-color : white;\r\n");
      out.write("\twidth : 60px;\r\n");
      out.write("\theight : 35px;\r\n");
      out.write("\tbox-shadow:none;\r\n");
      out.write("\tborder : 1px solid rgb(68, 114, 196);\r\n");
      out.write("\tcolor : rgb(68, 114, 196)\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" class=\"write\">\r\n");
      out.write("\t<tr height=\"35px\">\r\n");
      out.write("\t<td width=\"1000px\">\r\n");
      out.write("\t<select name=\"sick\">\r\n");
      out.write("\t\t<option selected> 카테고리 </option>\r\n");
      out.write("  \t\t<option> 두통 </option>\r\n");
      out.write("  \t\t<option> 복통 </option>\r\n");
      out.write("  \t\t<option> 바나나 </option>\r\n");
      out.write("  \t\t<option> 기타 </option>\r\n");
      out.write(" \t</select> </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"35px\">\r\n");
      out.write("\t<td width=\"1000px\">\r\n");
      out.write("\t<input type=\"text\" class=\"content\" style=\"height:35px; width:1000px\" value=\"제목\" name=\"title\" onfocus=\"this.value=''\">\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"500px\">\r\n");
      out.write("\t<td width=\"1000px\">\r\n");
      out.write("\t<input type=\"text\" class=\"content\" style=\"height:500px; width:1000px\" value=\"내용을 입력하세요\" name=\"title\" onfocus=\"this.value=''\">\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"submit\" class=\"submit\" value=\"등록\">\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
